name: F & C vont-ils partir
# see https://ogp.me/#types
type: website
url: https://florianeetclementvontilspartir.com/
image: https://avatars3.githubusercontent.com/u/447956?s=400&v=4
description: Viens donc voir si floriane et clément vont réussir à partir. Au mieux tu repars avec la console, au pire avec les bobettes sales.
